env: "dev"
port: 8023
host: "127.0.0.1"
name: "web-bff"
language: "zh"
page_size: 15
secret_key: "gin-randomkey-Xy8!YW&oboSl8a&E+LbiUguRogfO@Hci"
jwt_info:
  token_key: ""
  jwt_prefix: "Bearer "
  jwt_expire_hour: 24
  jwt_header_key: "Authorization"
  ksr_token_key: "gbvvZeIigTktBc1QarWY5CQuxnveeT88FkRayvU14CXXItERdIRgD+012+ifnJZDl6wu/A/4ITNldut1UBNJdA=="
datasource:
  mysql: "root:!Kyk666888@tcp(192.168.1.43:3306)/shop?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    host: "127.0.0.1"
    port: 6379
    pwd: ""
    db: 2
    pool_size: 10
log:
  level: "debug"
  path: "log" #  日志文件位置
  filename: "runtime/logs/mx_info.log"  # 日志文件名
  err_filename: "runtime/logs/mx_err.log"  # 日志文件名
  max_size: 100 # 进行切割之前,日志文件的最大大小(MB为单位)
  max_age: 100  # 保留旧文件的最大天数
  max_backups: 100 # 保留旧文件的最大个数
  compress: false # 是否压缩
  format: "json"  # 序列化格式